# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'together' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for together
	pod 'FlyoverKit', '~> 1.2.0'
	pod 'GoogleSignIn'

  target 'togetherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'togetherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
